modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="furnitureexpanded"
version="1.18-1.0.1" #${file.jarVersion}
displayName="Furniture Expanded"
logoFile="expanded.png"
authors="clumsycat"
description='''
Just a collection of furniture.
'''
[[dependencies.furnitureexpanded]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.furnitureexpanded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
