modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="furnitureexpanded"
version="1.19-1.1"
displayName="Furniture Expanded"
logoFile="expanded.png"
authors="clumsycat"
description='''
Just a collection of furniture.
'''
[[dependencies.furnitureexpanded]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.furnitureexpanded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
