modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="furnitureexpanded"
version="1.19.4-1.1"
displayName="Furniture Expanded"
logoFile="expanded.png"
authors="clumsycat"
description='''
Just a collection of furniture.
'''
[[dependencies.furnitureexpanded]] #optional
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.furnitureexpanded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
